jobs:
  specs:
    name: Run specs
    run_when:
      any branch has been updated:
        type: branch
        include_match: ^.*$
    context:
      generate_tasks:
        include_match: spec/.*_spec.rb
      task_defaults:
        include:
          - cider-ci/database_task-component.yml
          - cider-ci/ruby-bundle_task-component.yml
          - cider-ci/server_task-component.yml
          - cider-ci/uberjar_task-component.yml
        traits:
          JDK 8: true
          Leiningen 2: true
        ports:
          LEIHS_API_HTTP_PORT:
            min: 3200
            max: 3300
        environment_variables:
          API_DIR: '{{CIDER_CI_WORKING_DIR}}'
          DATABASE_NAME: leihs_api_{{CIDER_CI_TRIAL_ID}}
          LEIHS_DATABASE_URL: "jdbc:postgresql://localhost/{{DATABASE_NAME}}?max-pool-size=5"
          LEIHS_HTTP_BASE_URL: http://localhost:{{LEIHS_API_HTTP_PORT}}
          LEIHS_SECRET: '{{CIDER_CI_TRIAL_ID}}'
          RAILS_ENV: test
          RUBY: '{{RUBY_ENGINE}}-{{RUBY_VERSION}}'
          RUBY_ENGINE: ruby
          RUBY_VERSION: 2.4.3
        git_options:
          submodules:
            include_match: ^.*$
        scripts:
          test:
            body: |
              #!/usr/bin/env bash
              set -eux
              export PATH=~/.rubies/$RUBY/bin:$PATH
              mkdir -p log
              xvfb-run -a -e log/xvfb.log bundle exec rspec $CIDER_CI_TASK_FILE
