jobs:
  specs:
    name: Run specs
    run_when:
      any branch has been updated:
        type: branch
        include_match: ^.*$
    context:
      generate_tasks:
        include_match: spec/.*_spec.rb
      task_defaults:
        include:
          - cider-ci/database_task-component.yml
          - cider-ci/ruby-bundle_task-component.yml
          - cider-ci/server_task-component.yml
          - cider-ci/test-auth-system_task-component.yml
          - cider-ci/uberjar_task-component.yml
        traits:
          JDK 8: true
          Leiningen 2: true
        ports:
          LEIHS_MY_HTTP_PORT:
            min: 3240
            max: 3249
          TEST_AUTH_SYSTEM_PORT:
            min: 3240
            max: 3249
        environment_variables:
          MY_DIR: '{{CIDER_CI_WORKING_DIR}}'
          DATABASE_NAME: leihs_api_{{CIDER_CI_TRIAL_ID}}
          LEIHS_DATABASE_URL: "jdbc:postgresql://localhost/{{DATABASE_NAME}}?max-pool-size=5"
          LEIHS_MY_HTTP_BASE_URL: http://localhost:{{LEIHS_MY_HTTP_PORT}}
          LEIHS_SECRET: '{{CIDER_CI_TRIAL_ID}}'
          RAILS_ENV: test
          RUBY: '{{RUBY_ENGINE}}-{{RUBY_VERSION}}'
          RUBY_ENGINE: ruby
          RUBY_VERSION: 2.4.3
        git_options:
          submodules:
            include_match: ^.*$
        scripts:
          test:
            body: |
              #!/usr/bin/env bash
              set -eux
              export PATH=~/.rubies/$RUBY/bin:$PATH
              mkdir -p log
              xvfb-run -a -e log/xvfb.log bundle exec rspec $CIDER_CI_TASK_FILE
  good-to-merge:
    name: ⚑ Good To Merge
    description: |
      This job depends on all other tests and checks
      and it will pass if and only if all dependencies have passed.
      Status of this job is **used by github's "branch protection"**!
    depends_on: &GOOD_TO_MERGE_DEPENDENTS
      specs have passed:
        type: job
        job_key: specs
        states: [passed]
      good to merge of the database:
        job_key: good-to-merge
        type: job
        submodule: [database]
        states: [passed]
    run_when: *GOOD_TO_MERGE_DEPENDENTS
    priority: 999 # "empty" job = high priority
    context:
      task_defaults:
        max_trials: 1
      tasks:
        all relevant tests have passed:
          name: "All relevant tests have passed, thus good to merge"
          scripts:
            main:
              body: echo 'All relevant tests have passed' ; exit 0
